import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service · Lyriq',
  description: 'Lyriq Terms of Service',
};

export default function TermsPage() {
  return (
    <main className="max-w-3xl mx-auto px-6 py-12 text-neutral-200">
      <div className="mb-8 border border-amber-800/60 bg-amber-950/30 rounded-lg p-4 text-amber-200 text-sm">
        <strong className="font-semibold">Draft.</strong> This document is a starting
        template adapted for Lyriq&apos;s current, free, ad-free launch. It has
        <em> not</em> been reviewed by an attorney. Have counsel review before
        going into wide public use.
      </div>

      <h1 className="text-4xl font-black text-white tracking-tight mb-2">
        Terms of Service
      </h1>
      <p className="text-neutral-500 text-sm mb-10">
        Effective: 2026-07-05
      </p>

      <div className="space-y-8 text-sm leading-relaxed">

        <section>
          <h2 className="text-white text-lg font-bold mb-2">1. Acceptance</h2>
          <p>
            By accessing or using Lyriq (the &ldquo;Service&rdquo;), you agree to
            be bound by these Terms of Service. If you do not agree, do not use
            the Service.
          </p>
        </section>

        <section>
          <h2 className="text-white text-lg font-bold mb-2">2. What Lyriq Is</h2>
          <p>
            Lyriq is an AI-powered music criticism and commentary hobby project.
            The Service displays song lyrics sourced from third-party providers
            (currently Genius), community-contributed annotations, and
            AI-generated interpretive commentary. Lyriq does not own the underlying
            musical compositions or recordings, and does not claim any right in the
            lyrics themselves.
          </p>
        </section>

        <section>
          <h2 className="text-white text-lg font-bold mb-2">3. AI-Generated Content</h2>
          <p className="mb-2">
            The interpretive text on Lyriq is generated by a large language model
            (currently Anthropic&apos;s Claude). AI-generated content is:
          </p>
          <ul className="list-disc list-inside space-y-1 text-neutral-300">
            <li>Opinion and commentary, not statements of fact.</li>
            <li>Not endorsed by, or affiliated with, artists or rights holders.</li>
            <li>Subject to error, hallucination, or omission.</li>
            <li>Provided as-is for entertainment and educational purposes.</li>
          </ul>
          <p className="mt-2">
            You should not rely on AI-generated content for any factual,
            professional, journalistic, or critical decision-making.
          </p>
        </section>

        <section>
          <h2 className="text-white text-lg font-bold mb-2">4. No Accounts, No Payments</h2>
          <p>
            Lyriq currently has no user accounts and does not sell subscriptions,
            digital products, or physical goods. If that ever changes, these Terms
            will be updated in advance of enabling those features.
          </p>
        </section>

        <section>
          <h2 className="text-white text-lg font-bold mb-2">5. Acceptable Use</h2>
          <p className="mb-2">You agree not to:</p>
          <ul className="list-disc list-inside space-y-1 text-neutral-300">
            <li>Scrape, crawl, or bulk-download content from the Service.</li>
            <li>Reverse-engineer the Service or attempt to extract prompts or model outputs at scale.</li>
            <li>Use the Service to violate any law or third-party rights.</li>
            <li>Submit false abuse reports or copyright claims.</li>
            <li>Abuse the AI analysis feature to burn through Lyriq&apos;s monthly compute budget in bad faith.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-white text-lg font-bold mb-2">6. Intellectual Property</h2>
          <ul className="list-disc list-inside space-y-1 text-neutral-300">
            <li>Lyriq&apos;s AI-generated commentary is provided for your personal, non-commercial use.</li>
            <li>Lyrics, album art, and artist photos are sourced from third parties (Genius, Deezer) and remain the property of their respective rights holders.</li>
            <li>You retain all rights to anything you submit.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-white text-lg font-bold mb-2">7. Disclaimers</h2>
          <p className="uppercase text-neutral-400 text-xs leading-relaxed">
            The Service is provided &ldquo;as is&rdquo; without warranty of any
            kind. We disclaim all warranties, express or implied, including
            merchantability, fitness for a particular purpose, and
            non-infringement. We do not warrant that the Service will be
            uninterrupted, error-free, or continuously available.
          </p>
        </section>

        <section>
          <h2 className="text-white text-lg font-bold mb-2">8. Limitation of Liability</h2>
          <p className="uppercase text-neutral-400 text-xs leading-relaxed">
            To the maximum extent permitted by law, our total liability for any
            claim arising from your use of the Service shall not exceed one
            hundred U.S. dollars ($100).
          </p>
        </section>

        <section>
          <h2 className="text-white text-lg font-bold mb-2">9. DMCA / Copyright</h2>
          <p>
            If you believe content displayed on Lyriq infringes your copyright,
            send a DMCA takedown notice to{' '}
            <span className="font-mono text-neutral-400">hello@lyriq.example</span>{' '}
            with the subject line &ldquo;DMCA Takedown,&rdquo; containing the
            elements required by 17 U.S.C. § 512(c)(3). Lyriq responds to valid
            notices promptly and will remove infringing material without
            requiring a lawsuit.
          </p>
        </section>

        <section>
          <h2 className="text-white text-lg font-bold mb-2">10. Termination</h2>
          <p>
            We may suspend or discontinue the Service, or your access to it, at
            any time and for any reason, with or without notice.
          </p>
        </section>

        <section>
          <h2 className="text-white text-lg font-bold mb-2">11. Governing Law</h2>
          <p>
            These Terms are governed by the laws of the United States and the
            state of the operator&apos;s primary residence, without regard to
            conflict-of-law principles.
          </p>
        </section>

        <section>
          <h2 className="text-white text-lg font-bold mb-2">12. Changes</h2>
          <p>
            We may update these Terms at any time. The &ldquo;Effective&rdquo;
            date at the top of this page reflects the last revision. Continued
            use after changes constitutes acceptance.
          </p>
        </section>

        <section>
          <h2 className="text-white text-lg font-bold mb-2">13. Contact</h2>
          <p>
            Questions about these Terms:{' '}
            <span className="font-mono text-neutral-400">hello@lyriq.example</span>
          </p>
        </section>

      </div>
    </main>
  );
}
